server:
  port: 8084
spring:
  application:
    name: config-server
  cloud:
   config:
     server:
       git:
        uri: https://github.com/tavo1599/DAD.git
        search-paths: config-data
        username: tavo1599
        password: S@llucasolis15
        default-label: main
  security:
      user:
        name: root
        password: s3cr3t
